name: Enforce PR Base

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check-base-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check base branch
        if: github.event.pull_request.base.ref != 'custom-main'
        run: |
          echo "❌ PR must target 'custom-main'."
          exit 1
